#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=odoo

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Backup sources & data
# Note: the last argument is where to save this path, see the restore script.
ynh_backup "/home/${app}" "sources"
