#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# This is a multi-instance app, meaning it can be installed several times independently
# The id of the app as stated in the manifest is available as $YNH_APP_ID
# The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
# The app instance name is available as $YNH_APP_INSTANCE_NAME
#    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
#    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
#    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
# The app instance name is probably what you are interested the most, since this is
# guaranteed to be unique. This is a good unique identifier to define installation path,
# db names, ...
app=odoo

# Retrieve arguments
domain=$1
path='/'
admin=$2
admin_password=$3
database_password=$4
database_language=$5

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Save app settings
ynh_app_setting_set "$app" admin "$admin"
ynh_app_setting_set "$app" language "$database_language"

# Check domain/path availability
domain=${domain}"/"
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

domain=${domain%/}
sudo yunohost app setting $app domain -v $domain
if [ -f /usr/bin/openerp-server ]; then
	echo "Odoo is already installed, switching to multi-instances"
	sudo yunohost app setting $app instance -v "slave"
	
else
	echo "Installing odoo"
	sudo yunohost app setting $app version -v "9.0"
	sudo yunohost app setting $app instance -v "master"
	# Install Odoo
	# Prepare installation
		sudo apt-get -y -qq install curl

	# Install Odoo

		sudo sh -c 'echo "deb http://nightly.odoo.com/9.0/nightly/deb/ ./" > /etc/apt/sources.list.d/odoo.list'

		sudo apt-get update

		# Initialize installation
		sudo apt-get -y -qq install postgresql
		sudo su - postgres -c "echo \"CREATE USER odoo WITH PASSWORD '$admin_password' CREATEDB;\" | psql" 2> /dev/null || true 

		sudo apt-get -y -qq install odoo

	# Install wkhtmltopdf to print PDF reports
		sudo apt-get -yf -qq install wkhtmltopdf

	# Set admin password
		sudo sed -i "s@ADMIN_PASSWORD@$admin_password@g" ../conf/openerp-server.conf
		sudo cp ../conf/openerp-server.conf /etc/odoo/openerp-server.conf
		sudo chown odoo:odoo /etc/odoo/openerp-server.conf

	# Autoinstall the LDAP auth module
		sudo sed -i "s@'auto_install': False@'auto_install': True@g" /usr/lib/python2.7/dist-packages/openerp/addons/auth_ldap/__openerp__.py

	# Install oerplib to manage databases
		#sudo pip install oerplib

	# Add services
		sudo yunohost service add postgresql
		sudo yunohost service add odoo --log /var/log/odoo/odoo-server.log
		sudo yunohost service stop odoo
		sudo yunohost service start odoo
fi

function exit_properly
{
    set +e
    # TODO: uninstall db
    sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
    sudo service nginx reload
    exit 1
}
trap exit_properly ERR

sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

sudo yunohost app setting $app skipped_uris -v "/"

sudo service nginx reload
echo $?

# Reload services
sudo service nginx reload
