#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=odoo

# Upgrade official package
sudo apt-get install odoo -y -qq

# Reload nginx service
sudo service nginx reload
